
state_bird_list = {

    'montgomery': 'Yellowhammer',
    'juneau': 'Willow Ptarmigan',
    'phoenix': 'Cactus Wren',
    'little rock': 'Northern Mockingbird',
    'sacramento': 'California Quail',
    'denver': 'Lark Bunting',
    'hartford': 'American Robin',
    'dover': 'Delaware Blue Hen',
    'tallahassee': 'Northern Mockingbird',
    'atlanta': 'Brown Thrasher',
    'honolulu': 'Hawaiian Goose',
    'boise': 'Mountain Bluebird',
    'springfield': 'Northern Cardinal',
    'indianapolis': 'Northern Cardinal',
    'des moines': 'Eastern Goldfinch',
    'topeka': 'Western Meadowlark',
    'frankfort': 'Northern Cardinal',
    'baton rouge': 'Brown Pelican',
    'augusta': 'Chickadee',
    'annapolis': 'Baltimore Oriole',
    'boston': 'Black-capped Chickadee',
    'lansing': 'American Robin',
    'saint paul': 'Common Loon',
    'jackson': 'Northern Mockingbird',
    'jefferson city': 'Eastern Bluebird',
    'helena': 'Western Meadowlark',
    'lincoln': 'Western Meadowlark',
    'carson city': 'Mountain Bluebird',
    'concord': 'Purple Finch',
    'trenton': 'Eastern Goldfinch',
    'santa fe': 'Greater Roadrunner',
    'albany': 'Eastern Bluebird',
    'raleigh': 'Northern Cardinal',
    'bismarck': 'Western Meadowlark',
    'columbus': 'Northern Cardinal',
    'oklahoma city': 'Scissor-tailed Flycatcher',
    'salem': 'Western Meadowlark',
    'harrisburg': 'Ruffed Grouse',
    'providence': 'Rhode Island Red Hen',
    'columbia': 'Carolina Wren',
    'pierre': 'Ring-necked Pheasant',
    'nashville': 'Northern Mockingbird',
    'austin': 'Northern Mockingbird',
    'salt lake city': 'California Gull',
    'montpelier': 'Hermit Thrush',
    'richmond': 'Northern Cardinal',
    'olympia': 'Willow Goldfinch',
    'charleston': 'Northern Cardinal',
    'madison': 'American Robin',
    'cheyenne': 'Western Meadowlark'

}

def SetBird(city):

    return state_bird_list[city]