
state_bird_list = {

    'montgomery': 'Yellowhammer',
    'juneau': 'Willow Ptarmigan',
    'phoenix': 'Cactus Wren',
    'little rock': 'Northern Mockingbird',
    'sacramento': 'California Quail',
    'denver': 'Lark Bunting',
    'hartford': 'American Robin',
    'dover': 'Delaware Blue Hen',
    'tallahassee': 'Northern Mockingbird',
    'atlanta': 'Brown Thrasher',
    'honolulu': 'Hawaiian Goose',
    'boise': 'Mountain Bluebird',
    'springfield': 'Northern Cardinal',
    'indianapolis': 'Northern Cardinal',
    'des moines': 'Eastern Goldfinch',
    'topeka': 'Western Meadowlark',
    'frankfort': 'Northern Cardinal',
    'baton rouge': 'Brown Pelican',
    'augusta': 'Chickadee',
    'annapolis': 'Baltimore Oriole',
    'boston': 'Black-capped Chickadee',
    'lansing': 'American Robin',
    'saint paul': 'Common Loon',
    'jackson': 'Northern Mockingbird',
    'jefferson city': 'Eastern Bluebird',
    'helena': 'Western Meadowlark',
    'lincoln': 'Western Meadowlark',
    'carson city': 'Mountain Bluebird',
    'concord': 'Purple Finch',
    'trenton': 'Eastern Goldfinch',
    'santa fe': 'Greater Roadrunner',
    'albany': 'Eastern Bluebird',
    'raleigh': 'Northern Cardinal',
    'bismarck': 'Western Meadowlark',
    'columbus': 'Northern Cardinal',
    'oklahoma city': 'Scissor-tailed Flycatcher',
    'salem': 'Western Meadowlark',
    'harrisburg': 'Ruffed Grouse',
    'providence': 'Rhode Island Red Hen',
    'columbia': 'Carolina Wren',
    'pierre': 'Ring-necked Pheasant',
    'nashville': 'Northern Mockingbird',
    'austin': 'Northern Mockingbird',
    'salt lake city': 'California Gull',
    'montpelier': 'Hermit Thrush',
    'richmond': 'Northern Cardinal',
    'olympia': 'Willow Goldfinch',
    'charleston': 'Northern Cardinal',
    'madison': 'American Robin',
    'cheyenne': 'Western Meadowlark'

}

state_flower_list = {
    
    'montgomery': 'Camellia',
    'juneau': 'Forget-me-not',
    'phoenix': 'Saguaro Cactus Blossom',
    'little rock': 'Apple Blossom',
    'sacramento': 'California Poppy',
    'denver': 'Rocky Mountain Columbine',
    'hartford': 'Mountain Laurel',
    'dover': 'Peach Blossom',
    'tallahassee': 'Orange Blossom',
    'atlanta': 'Cherokee Rose',
    'honolulu': 'Hibiscus',
    'boise': 'Syringa',
    'springfield': 'Purple Violet',
    'indianapolis': 'Peony',
    'des moines': 'Wild Prairie Rose',
    'topeka': 'Sunflower',
    'frankfort': 'Goldenrod',
    'baton rouge': 'Magnolia',
    'augusta': 'White Pine Cone and Tassel',
    'annapolis': 'Black-eyed Susan',
    'boston': 'Mayflower',
    'lansing': 'Apple Blossom',
    'saint paul': 'Pink and White Lady\'s Slipper',
    'jackson': 'Magnolia',
    'jefferson city': 'White Hawthorn Blossom',
    'helena': 'Bitterroot',
    'lincoln': 'Goldenrod',
    'carson city': 'Sagebrush',
    'concord': 'Purple Lilac',
    'trenton': 'Violet',
    'santa fe': 'Yucca Flower',
    'albany': 'Rose',
    'raleigh': 'Dogwood Blossom',
    'bismarck': 'Wild Prairie Rose',
    'columbus': 'Scarlet Carnation',
    'oklahoma city': 'Mistletoe',
    'salem': 'Oregon Grape',
    'harrisburg': 'Mountain Laurel',
    'providence': 'Violet',
    'columbia': 'Yellow Jessamine',
    'pierre': 'Pasque Flower',
    'nashville': 'Iris',
    'austin': 'Bluebonnet',
    'salt lake city': 'Sego Lily',
    'montpelier': 'Red Clover',
    'richmond': 'American Dogwood',
    'olympia': 'Coast Rhododendron',
    'charleston': 'Rhododendron',
    'madison': 'Wood Violet',
    'cheyenne': 'Indian Paintbrush'
}


def SetFlower(city):

    return state_flower_list[city]