# Generated by Django 5.0.2 on 2024-04-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoGuessr', '0003_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_score',
            name='playerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoGuessr.user'),
        ),
    ]
