# Generated by Django 5.0.3 on 2024-04-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoGuessr', '0005_rename_playerid_game_score_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_score',
            old_name='username',
            new_name='playerID',
        ),
    ]
