# Generated by Django 5.0.3 on 2024-04-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoGuessr', '0006_rename_username_game_score_playerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_score',
            name='playerID',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
